FROM codelabs_base:latest as base
COPY ./labs /codelabs/site/codelabs
RUN ./process-labs.sh

FROM nginx:1.16.1 as final
COPY --from=base /output /usr/share/nginx/html

COPY bootstrap.sh /work/bootstrap.sh
COPY ./write-config/write-config /work/write-config
WORKDIR /work
CMD ["/bin/sh", "-c", "/work/bootstrap.sh"]
