# yaml resource file for deployment from skaffold

apiVersion: v1
kind: Namespace
metadata:
  name: "localtest"
  labels: 
    name: "localtest"
        
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "localtest"
  namespace: localtest  
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: localtest
        track: stable
        version: 0.1.0
    spec:
      containers:
        - name: localtest
          image: nginx:1.16.1
          imagePullPolicy: Always
          ports:
            - name: api
              containerPort: 8080
          env:
            - name: PORT
              value: "8080"

          resources:
            limits:
              cpu: "1"            
            requests:
              cpu: "10m"

